version: '3'

networks:
  bridge:
    driver: bridge
    ipam:
        config:
        - subnet: 172.17.0.0/16

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest # remember to change this if you're using rpi
    networks:
      bridge:
        ipv4_address: 172.17.0.7
      proxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "85:80/tcp"
    #- "443:443/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: '172.17.0.8#5053'
    volumes:
      - '/home/kannymanny/Docker/Unbound/Data/Pi-hole/etc-pihole/:/etc/pihole/'
      - '/home/kannymanny/Docker/Unbound/Data/Pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest # remember to change this if you're using rpi
    networks:
      bridge:
        ipv4_address: 172.17.0.8
    volumes:
      - /home/kannymanny/Docker/Unbound:/opt/unbound/etc/unbound
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped
