version: "2"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #group_add:
    #  - '109'  # This needs to be the group id of running `stat -c '%g' /dev/dri/renderD128` on the docker host
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /home/kannymanny/Data/jellyfin/config:/config
      - /home/kannymanny/Data/jellyfin/cache:/cache
      - /home/smbuser/Shared/HDD/Media/Movies:/Films:ro
      - /home/smbuser/Shared/HDD/Media/Web-series:/TVShows:ro
      #- /home/ubuntu/YOUR_NAS/Audiobooks:/Audiobooks:ro
      #- /home/ubuntu/YOUR_NAS/Music:/Music:ro
    ports:
      - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    #devices: uncomment these and amend if you require GPU accelerated transcoding
    #  - /dev/dri/renderD128:/dev/dri/renderD128
    #  - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
